# Generated by Django 5.0 on 2024-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_audioresource_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioresource",
            name="thumbnail_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="audioresource",
            name="video_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="audioresource",
            name="video_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
