# Generated by Django 5.0 on 2024-02-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_audioresource_thumbnail_url_audioresource_video_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioresource",
            name="audio",
            field=models.FileField(upload_to="uploads"),
        ),
    ]
